name: Phantom APK Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Buildozer'ın izin sorunlarını aşması için çalışma alanını temizliyoruz
      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER .

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: master

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Phantom-APK
          path: bin/*.apk
